<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Welcome  MANLANGIT                       _04e7c0</name>
   <tag></tag>
   <elementGuidId>55cb2a1f-3374-4937-88ad-441506faddea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='WelcomeLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WelcomeLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d7084b5-580a-4b6c-aa5a-6d774bbaf3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>11fb112f-1786-4d3e-8a3f-e4645c9339c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>8d7ab92c-29c2-4abc-a976-e6ac965fcb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>fc4f0f7b-06d1-4ed0-b970-6381e98c55e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WelcomeLabel</value>
      <webElementGuid>80830aaf-c1b6-41c4-8337-7174f682bd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Welcome  MANLANGIT                        Admin   					               		HEAD OFFICE					               		System Date: 2023-05-10 Status: Open</value>
      <webElementGuid>695f459c-3bcd-4ce6-aee6-ef30d1ff26c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WelcomeLabel&quot;)</value>
      <webElementGuid>640431ed-7d1a-42f2-8b77-1d5b4ec800a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='WelcomeLabel']</value>
      <webElementGuid>9577bf0e-f627-473e-a79c-b3e065ac0b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/nav/ul/li[3]/a</value>
      <webElementGuid>2c12a539-15b5-4d9e-a2e4-0107c45c109f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[2]</value>
      <webElementGuid>3c79cbc3-fe48-42ce-8894-7052964f1139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome']/parent::*</value>
      <webElementGuid>c0b0e809-c24c-4b86-80c4-a6698c9cb25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>326e5b26-eb00-4824-866c-594e745011a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>8b092035-d8b3-41ce-904d-7b6e10d61a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'WelcomeLabel' and (text() = '
                            Welcome  MANLANGIT                        Admin   					               		HEAD OFFICE					               		System Date: 2023-05-10 Status: Open' or . = '
                            Welcome  MANLANGIT                        Admin   					               		HEAD OFFICE					               		System Date: 2023-05-10 Status: Open')]</value>
      <webElementGuid>0f9107cc-7185-46a2-8993-074645076024</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
