<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search</name>
   <tag></tag>
   <elementGuidId>ad96c2f5-65c1-4484-a23e-ace5bf030048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reportTable_filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reportTable_filter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5906f1fe-f623-4f65-8d18-eee21faf9013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reportTable_filter</value>
      <webElementGuid>d1dfa9d6-960d-48ae-ae85-46cf7d87c6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_filter</value>
      <webElementGuid>6dcb2770-06b1-469f-b749-9447d9de96b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search:</value>
      <webElementGuid>dc073cb8-6027-46f6-aa57-d3884819fa45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportTable_filter&quot;)</value>
      <webElementGuid>1d5939f9-3060-43de-a59e-0f894934d6e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='reportTable_filter']</value>
      <webElementGuid>56331434-6626-4a9c-ba5d-67fcbfad5060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reportTable_wrapper']/div/div[2]/div</value>
      <webElementGuid>170602ff-daa3-4faa-ad24-741192ad3e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Users'])[1]/following::div[7]</value>
      <webElementGuid>110bcd99-1a3d-4ff0-ab4d-5f8abb909ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff ID No.'])[1]/preceding::div[1]</value>
      <webElementGuid>65948ff3-b039-41c1-8fe3-53ceb8705ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>59bd3809-45a2-4031-9c9a-c4ded0afe4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'reportTable_filter' and (text() = 'Search:' or . = 'Search:')]</value>
      <webElementGuid>2d129e07-cb12-40df-9f8d-24d7157841a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
