<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select Item--Cebu 5Cebu 6Cebu 7Ce_aa1df1</name>
   <tag></tag>
   <elementGuidId>ce2af9da-5c63-45ac-b5f4-f1d7bc598506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='StaffArea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#StaffArea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>828832ae-8776-457c-a0fe-9ea8df86dca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>40259fb4-55e7-40c2-8f0f-d87666c0bc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StaffArea</value>
      <webElementGuid>b6a823c0-6c58-4e57-b7e1-619ead026bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select Item--Cebu 5Cebu 6Cebu 7Cebu 8Cebu 9</value>
      <webElementGuid>91c40d9e-c1a6-4cdc-8409-c32003b07a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StaffArea&quot;)</value>
      <webElementGuid>a5f10677-c160-4525-991a-917319e022b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='StaffArea']</value>
      <webElementGuid>88fdab1a-1c7d-4cb2-ac4f-43238355e918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserManagementModal']/div/div/div[2]/div[2]/div[3]/select</value>
      <webElementGuid>d390f9df-fd65-47ab-b685-c54218e78345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area'])[2]/following::select[1]</value>
      <webElementGuid>3593ed6a-e94e-449c-9e07-97b6725f2331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[1]/following::select[2]</value>
      <webElementGuid>5cce854b-5b64-4a1d-a22f-607d9341b9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>79ad269d-da10-40bf-9ba5-07ad93f45e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[1]/preceding::select[1]</value>
      <webElementGuid>4061feeb-7dd1-4e60-a4f5-c499ea653b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>2217359b-af66-4c18-a2da-c5be2272c6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'StaffArea' and (text() = '---Select Item--Cebu 5Cebu 6Cebu 7Cebu 8Cebu 9' or . = '---Select Item--Cebu 5Cebu 6Cebu 7Cebu 8Cebu 9')]</value>
      <webElementGuid>f8840ff5-07d9-4d71-9461-af311ce09cee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
