<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select Item--Branch 1Ilocos 1Iloc_37e864</name>
   <tag></tag>
   <elementGuidId>dd16d800-7588-4b81-8a2c-eac7964ae40a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='StaffArea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#StaffArea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c228b1e3-67eb-4319-8ef6-768fd499fb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>69e4e4cd-3f2e-46c6-a3f2-69f88bb9e518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StaffArea</value>
      <webElementGuid>60dc0daf-f5af-4813-b1f4-cd9a28fa9b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select Item--Branch 1Ilocos 1Ilocos 2Ilocos 2 DISSOLVE (7/24/2020)Ilocos 3Ilocos 4Ilocos 5test area</value>
      <webElementGuid>ff52c776-40b6-407c-99e1-c33df12288a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StaffArea&quot;)</value>
      <webElementGuid>739dc2f6-a892-4d91-bd59-84ce6203935e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='StaffArea']</value>
      <webElementGuid>872cbb48-797a-4ad3-b7c7-55a62d31d70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserManagementModal']/div/div/div[2]/div[2]/div[3]/select</value>
      <webElementGuid>28e7df71-5553-493f-9af7-e5291ce09a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area'])[2]/following::select[1]</value>
      <webElementGuid>e896f8b8-638d-40d8-be55-54d2d40bd416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[1]/following::select[2]</value>
      <webElementGuid>4af55d4e-ce13-4fd3-b5ba-780db78bf7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>8ca0aa25-6e2e-4bad-a3b8-4fd2b0f92a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Changes'])[1]/preceding::select[1]</value>
      <webElementGuid>6e1bab8b-a759-4882-93b3-5149a9121d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>014b1ed4-85ea-46e5-8306-1ba5a2bd2c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'StaffArea' and (text() = '---Select Item--Branch 1Ilocos 1Ilocos 2Ilocos 2 DISSOLVE (7/24/2020)Ilocos 3Ilocos 4Ilocos 5test area' or . = '---Select Item--Branch 1Ilocos 1Ilocos 2Ilocos 2 DISSOLVE (7/24/2020)Ilocos 3Ilocos 4Ilocos 5test area')]</value>
      <webElementGuid>8a34a6e5-9235-4dd5-9273-6a281c6d598c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
