<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select Item--General ClerkBookkee_48559c</name>
   <tag></tag>
   <elementGuidId>9fc597f7-dd3f-422f-966e-f9087fb6a74c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Position']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Position</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>942e3eab-70d6-41a9-800f-88bad2e77fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Position</value>
      <webElementGuid>bbdb2dba-cadf-4fe3-9e55-cba235c19854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>90d259d9-9548-4b7e-ae35-61dd64ddc02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select Item--General ClerkBookkeeperFinance BookkeeperCashierUnit ManagerFinance OfficerAccount ManagerSupervisionArea ManagerAccounting ManagerCluster AccountantAccounting OfficerFinance ManagerDirector for Finance and AdminRegional DirectorRegional AccountantGeneral AccountantExecutive DirectorDeputy Director for DCCDeputy Director for FinanceDirector for complianceAdminAuditCluster ITDeputy Executive Director for Finance and Admin</value>
      <webElementGuid>a79aad3e-0bc9-4062-9392-5eafe2c9afdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Position&quot;)</value>
      <webElementGuid>0df2fb12-39b4-4b56-b7bf-11d26eafacd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Position']</value>
      <webElementGuid>47f96490-5563-4641-b471-9a50c6c30fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserManagementModal']/div/div/div[2]/div[2]/div/select</value>
      <webElementGuid>501bfe91-7e54-4496-8d18-c47bef455a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position'])[2]/following::select[1]</value>
      <webElementGuid>9df33a63-df33-4a08-ac7b-b80d2dcc76e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Phone'])[1]/following::select[1]</value>
      <webElementGuid>e0718491-53da-48f6-a44e-e79bd990a7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[1]/preceding::select[1]</value>
      <webElementGuid>e137a911-9024-49f8-b713-28105edefc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area'])[2]/preceding::select[2]</value>
      <webElementGuid>6b60056a-cbaf-47dd-8faa-617450a6175c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>c2273398-3af4-4812-9ae3-f5026387223f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Position' and (text() = '---Select Item--General ClerkBookkeeperFinance BookkeeperCashierUnit ManagerFinance OfficerAccount ManagerSupervisionArea ManagerAccounting ManagerCluster AccountantAccounting OfficerFinance ManagerDirector for Finance and AdminRegional DirectorRegional AccountantGeneral AccountantExecutive DirectorDeputy Director for DCCDeputy Director for FinanceDirector for complianceAdminAuditCluster ITDeputy Executive Director for Finance and Admin' or . = '---Select Item--General ClerkBookkeeperFinance BookkeeperCashierUnit ManagerFinance OfficerAccount ManagerSupervisionArea ManagerAccounting ManagerCluster AccountantAccounting OfficerFinance ManagerDirector for Finance and AdminRegional DirectorRegional AccountantGeneral AccountantExecutive DirectorDeputy Director for DCCDeputy Director for FinanceDirector for complianceAdminAuditCluster ITDeputy Executive Director for Finance and Admin')]</value>
      <webElementGuid>b80c53f5-7509-4ccf-9357-c51d08ca3e02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
