<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Active_userStatus1000</name>
   <tag></tag>
   <elementGuidId>d69eca74-c92d-42cd-8af7-e01fc8e2d347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='userStatus1000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userStatus1000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1685578-0a8b-4bb5-acd4-e5d3a2c2efde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userStatus1000</value>
      <webElementGuid>1ba2a889-967e-438d-80c6-9e3af2aca50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>deactivate</value>
      <webElementGuid>514a65b7-5c56-44b8-b0e0-2e621138bb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times-circle fa-2x</value>
      <webElementGuid>3ff5234e-0b20-4dd0-ab52-0f5c661b46f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userStatus1000&quot;)</value>
      <webElementGuid>89efcfcd-f758-4d1e-a37c-4695eca7b8f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='userStatus1000']</value>
      <webElementGuid>5e71c53c-603f-42e4-8e1d-b1cc7e076fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='reportTable']/tbody/tr/td[12]/a/span</value>
      <webElementGuid>f1621f72-4ad2-4884-a2ec-77ef6e69079d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/a/span</value>
      <webElementGuid>20112a3e-69a4-433e-8010-820d4a1eee7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'userStatus1000']</value>
      <webElementGuid>fca2d0d6-ac0b-4d72-9d0c-958c388c5a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
