<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Active_fa fa-edit fa-2x</name>
   <tag></tag>
   <elementGuidId>0dc522b2-8174-45e4-92cd-f605087e8cbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='reportTable']/tbody/tr/td[10]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-edit.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2d0f179a-fd44-4846-ab60-4748c939ca5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit fa-2x</value>
      <webElementGuid>03e9aa70-89d4-4131-b3c3-439a1b3c3c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[10]/a[@class=&quot;ShowForm&quot;]/span[@class=&quot;fa fa-edit fa-2x&quot;]</value>
      <webElementGuid>3ac79e42-db1b-4a71-bdad-ac4a35fdc0b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='reportTable']/tbody/tr/td[10]/a/span</value>
      <webElementGuid>e001b9f6-6877-426b-b88d-97f0c13b04ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/a/span</value>
      <webElementGuid>1b9aeb51-dbc9-4fd9-a23c-9efba0f30b3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
