<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Inactive_userStatus1002</name>
   <tag></tag>
   <elementGuidId>a755a456-73d7-4fd3-941d-18ee5a0a3731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='userStatus1002']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userStatus1002</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3151ea74-6724-4c30-a1b5-056a963e565d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userStatus1002</value>
      <webElementGuid>1741a83c-907f-4ce6-a11a-e4064516700b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>activate</value>
      <webElementGuid>b5a661b8-c4f7-4ea0-8e06-4ab39e628217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check-circle fa-2x</value>
      <webElementGuid>014b3bd7-aa46-4c0a-81e2-3632ba6d87e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userStatus1002&quot;)</value>
      <webElementGuid>3e9418a0-8990-4df6-adfa-e2a2395de59e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='userStatus1002']</value>
      <webElementGuid>d51a714b-4115-4d75-ac67-1c3868ae35d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='reportTable']/tbody/tr[3]/td[12]/a/span</value>
      <webElementGuid>44dce4af-cb77-49c8-a0cc-59077d059219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[12]/a/span</value>
      <webElementGuid>e41dbe62-a56f-4395-a812-95e8d8333376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'userStatus1002']</value>
      <webElementGuid>a4d79ec8-8f3e-4a37-9338-714fcbbf6b64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
