<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>30fc05b4-f200-4a80-8171-d7af75deae23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='reportTable']/tbody/tr/td[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(12)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5d3a3f38-532f-4a71-b05b-b01e4a349a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[12]</value>
      <webElementGuid>6a96f972-5842-4e0c-90ef-76f83e79b7f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='reportTable']/tbody/tr/td[12]</value>
      <webElementGuid>c23e6581-beab-4573-af2b-7e711716cc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::td[3]</value>
      <webElementGuid>e6552407-35da-4e86-ab8c-528fd37848cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rhenz.losuegro@cardmri.com'])[1]/following::td[5]</value>
      <webElementGuid>d04b0b03-e27e-4a54-8ba7-716080a2bc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jcdaraug'])[1]/preceding::td[2]</value>
      <webElementGuid>0026ac07-a142-4c02-b6ad-28ada23d219c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Manager'])[2]/preceding::td[3]</value>
      <webElementGuid>8135ef10-20a9-4f6f-8883-11692b8de399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]</value>
      <webElementGuid>4aa56ff3-d06c-483e-adae-431d7ae619e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
