<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select Item--General ClerkBookkee_48559c</name>
   <tag></tag>
   <elementGuidId>c7706f86-3732-4577-9d6c-fa93d130e551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRolePosition']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboRolePosition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5ea2b551-7f2b-4ef1-8367-42ba254da4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRolePosition</value>
      <webElementGuid>2152d608-90e4-49e5-ac46-ddfadad28e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f27d3994-353c-447e-9c68-69c394ef9d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select Item--General ClerkBookkeeperFinance BookkeeperCashierUnit ManagerFinance OfficerAccount ManagerSupervisionArea ManagerAccounting ManagerCluster AccountantAccounting OfficerFinance ManagerDirector for Finance and AdminRegional DirectorRegional AccountantGeneral AccountantExecutive DirectorDeputy Director for DCCDeputy Director for FinanceDirector for complianceAdminAuditCluster ITDeputy Executive Director for Finance and Admin</value>
      <webElementGuid>4ab4ba3a-9e0f-4e24-a5bf-778e6153179d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRolePosition&quot;)</value>
      <webElementGuid>2377823b-afae-4b14-9166-cc06f4318b90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRolePosition']</value>
      <webElementGuid>aaf05de8-bb41-46ec-ab0a-ac278dad9f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div/div/div/select</value>
      <webElementGuid>87ec89c0-7ee9-4398-88c2-a7fdab5eac2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position:'])[1]/following::select[1]</value>
      <webElementGuid>addd7f78-9b1b-4420-970d-209280c34848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Roles'])[2]/following::select[1]</value>
      <webElementGuid>d8bc5a15-2e7f-4824-bc37-72bab4063029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a11af493-d3b4-4f3b-beb5-d5e1d9fad748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRolePosition' and (text() = '---Select Item--General ClerkBookkeeperFinance BookkeeperCashierUnit ManagerFinance OfficerAccount ManagerSupervisionArea ManagerAccounting ManagerCluster AccountantAccounting OfficerFinance ManagerDirector for Finance and AdminRegional DirectorRegional AccountantGeneral AccountantExecutive DirectorDeputy Director for DCCDeputy Director for FinanceDirector for complianceAdminAuditCluster ITDeputy Executive Director for Finance and Admin' or . = '---Select Item--General ClerkBookkeeperFinance BookkeeperCashierUnit ManagerFinance OfficerAccount ManagerSupervisionArea ManagerAccounting ManagerCluster AccountantAccounting OfficerFinance ManagerDirector for Finance and AdminRegional DirectorRegional AccountantGeneral AccountantExecutive DirectorDeputy Director for DCCDeputy Director for FinanceDirector for complianceAdminAuditCluster ITDeputy Executive Director for Finance and Admin')]</value>
      <webElementGuid>95a0ad83-f725-4aeb-bd67-f031c5b642c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
